-- require('hlslens').setup(opts or {})
--
-- local kbd = vim.keymap.set
-- local kopts = {noremap = true, silent = true}
--
-- kbd('n', 'n', [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]], kopts)
-- kbd('n', 'N', [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]], kopts)
-- kbd('n', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
-- kbd('n', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
-- kbd('n', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
-- kbd('n', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)
