local utils = {}
local type_utils = require 'lua-utils.type'
local list = require 'lua-utils.list'
local dict = require 'lua-utils.dict'
local copy = require 'lua-utils.copy'
local fs = require 'lua-utils.fs'
local set = require 'lua-utils.set'
local str = require 'lua-utils.string'

utils.str = str
utils.Result = type_utils.Result
utils.Ok = type_utils.Result.Ok
utils.Err = type_utils.Result.Err
utils.TypeError = type_utils.TypeError
utils.CallError = type_utils.CallError
utils.UnwrapError = type_utils.UnwrapError
utils.is = type_utils.is
utils.class = type_utils.class
utils.inspect = type_utils.inspect
utils.dump = type_utils.dump
utils.pp = type_utils.pp
utils.NIL = package.user.NIL
utils.as_value = package.user.lib.as_value
utils.is_nil = package.user.lib.is_nil
utils.rtostring = type_utils.rtostring
utils.is_result = type_utils.is.Result
utils.is_ok = type_utils.is.Ok
utils.is_err = type_utils.is.Err
utils.is_table = type_utils.is.table
utils.is_string = type_utils.is.string
utils.is_number = type_utils.is.number
utils.is_userdata = type_utils.is.userdata
utils.is_function = type_utils.is.fun
utils.is_boolean = type_utils.is.boolean
utils.is_thread = type_utils.is.thread
utils.is_list = type_utils.is.list
utils.is_dict = type_utils.is.dict
utils.is_pure_table = type_utils.is.pure_table
utils.is_class = type_utils.is.class
utils.is_instance = type_utils.is.instance
utils.is_error = type_utils.is.error
utils.is_object = type_utils.is.object
utils.as = type_utils.as
utils.as_number = type_utils.as.number
utils.as_integer = type_utils.as.integer
utils.as_function = type_utils.as.fun
utils.as_boolean = type_utils.as.boolean
utils.as_string = type_utils.as.string
utils.any_of = type_utils.is.any_of
utils.all_of = type_utils.is.all_of
utils.union = type_utils.is.union
utils.maybe = type_utils.is.maybe
utils.Error = type_utils.Error
utils.CallError = type_utils.Error.CallError
utils.TypeError = type_utils.Error.TypeError
utils.UnwrapError = type_utils.Error.UnwrapError
utils.list = list
utils.dict = dict
utils.copy = copy
utils.fs = fs
utils.path = fs
utils.set = set

return utils
